module.exports = {
    UNSUPPORTED_TYPE: 'UNSUPPORTED_TYPE',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    NO_FILE: 'NO_FILE',
    FAILED_TO_VALIDATE: 'FAILED_TO_VALIDATE',
    MALWARE_CHECK_ERROR: 'MALWARE_CHECK_ERROR',
    MALWARE_FOUND: 'MALWARE_FOUND',
    CONVERSION_ERROR: 'CONVERSION_ERROR',
    CONVERSION_OK: 'CONVERSION_OK'
};
